# Template PHP Build

# This template allows you to validate your PHP application.
# The workflow allows running tests and code linting on the default branch.

image: php:8.1

pipelines:
  default:
    - step:
        name: Install Dependencies
        script:
          - apt-get update && apt-get install -y unzip libzip-dev
          - docker-php-ext-install zip
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install --no-interaction
        caches:
          - composer

  branches:
    main:
      # - step:
      #     name: Run Tests
      #     script:
      #       - php artisan test
      - step:
          name: Run Pint
          script:
            - composer run pint
